# Generated by Django 4.0.3 on 2022-04-29 12:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/')),
        ),
    ]
