# Generated by Django 4.0.3 on 2022-04-29 12:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Admin\\Desktop\\saurav\\annotate 2\\media'), upload_to=''),
        ),
    ]
